name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  GB_BUILD_TYPE: Release
  VK_SDK_PATH: C:\VulkanSDK\1.2.162.0
  VULKAN_SDK: C:\VulkanSDK\1.2.162.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
      
    - name: Setup Vulkan
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.162.0/windows/VulkanSDK-1.2.162.0-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();

    - name: Build external libraries and projects
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build_vs2019

    - name: Build Game Bits
      working-directory: ${{github.workspace}}/build
      shell: cmd
      run: cmake --build . --config %GB_BUILD_TYPE%

    - name: Test Game Bits
      working-directory: ${{github.workspace}}/build
      shell: cmd
      run: ctest -C %GB_BUILD_TYPE%

    - name: Build Block World
      working-directory: ${{github.workspace}}/build/examples/block-world
      shell: cmd
      run: cmake --build . --config %GB_BUILD_TYPE% --target block_world
